name: "MSBuild Test Action"
author: "Daniele Tentoni"
branding:
  icon: "sun"
  color: "green"
description: "Run a test command using MSBuild and create test result artifacts."
inputs:
  example:
    description: "Input example"
    default: false
    required: false
outputs:
  result:
    description: "Result of the action."
    value: ${{ steps.run-tests.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: run-tests
      run: |
        echo "Hello World"
        echo "::set-output name=result::0"
      shell: pwsh
