name: "MSBuild Test Action"
author: "Daniele Tentoni"
branding:
  icon: "sun"
  color: "green"
description: "Run a test command using MSBuild and create test result artifacts."
inputs:
  solution:
    description: "Solution name"
    default: "#"
    required: false
outputs:
  nuget-packages-restored:
    description: "True if nuget packages was been restored"
    value: ${{ steps.nuget-restore.outputs.restored }}
  result:
    description: "Result of the action."
    value: ${{ steps.run-tests.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Restore Nuget Packages
      id: nuget-restore
      run: |
        if ( ${{ inputs.solution != '#' }} )
        {
          echo "Restoring Nuget Packages for ${{ inputs.solution }} solution"
          $(nuget restore ${{ inputs.solution }})
          if ( $? )
          {
            echo "::set-output name=restored::true"
          }
          else
          {
            echo "::set-output name=restored::false"
          }
        }
        else
        {
          echo "::set-output name=restored::false"
        }
      shell: pwsh

    - id: run-tests
      run: |
        echo "Hello World"
        echo "::set-output name=result::0"
      shell: pwsh
